# Generated by Django 5.1.5 on 2025-03-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
