# Generated by Django 5.1.5 on 2025-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
