# Generated by Django 5.1.5 on 2025-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='123456Qq', max_length=100, verbose_name='Password'),
        ),
    ]
